apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: monorepo-sample-service
spec:
  type: url
  targets:
    - https://github.com/RoadieHQ/monorepo-sample-service/blob/master/backstage-stuff/pricing-index.yaml
    - https://github.com/RoadieHQ/monorepo-sample-service/blob/master/backstage-stuff/banana-index.yaml
