apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: monorepo-sample-service
spec:
  type: url
  targets:
    - ./backstage-stuff/pricing-index.yaml
    - ./backstage-stuff/banana-index.yaml
