---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-7
  title: Service 7
  description: Component for Backstage 7
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
