---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-75
  title: Service 75
  description: Component for Backstage 75
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
