---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-174
  title: Service 174
  description: Component for Backstage 174
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
