---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-152
  title: Service 152
  description: Component for Backstage 152
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
