---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-200
  title: Service 200
  description: Component for Backstage 200
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
