---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-66
  title: Service 66
  description: Component for Backstage 66
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
