---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-117
  title: Service 117
  description: Component for Backstage 117
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
