---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-108
  title: Service 108
  description: Component for Backstage 108
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
