---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-6
  title: Service 6
  description: Component for Backstage 6
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
