---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-155
  title: Service 155
  description: Component for Backstage 155
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
