---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-137
  title: Service 137
  description: Component for Backstage 137
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
