---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-192
  title: Service 192
  description: Component for Backstage 192
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
