---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-89
  title: Service 89
  description: Component for Backstage 89
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
