---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-114
  title: Service 114
  description: Component for Backstage 114
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
