---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-41
  title: Service 41
  description: Component for Backstage 41
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
