---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-101
  title: Service 101
  description: Component for Backstage 101
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
