---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-193
  title: Service 193
  description: Component for Backstage 193
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
