---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-161
  title: Service 161
  description: Component for Backstage 161
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
