---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-147
  title: Service 147
  description: Component for Backstage 147
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
