---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-187
  title: Service 187
  description: Component for Backstage 187
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
