---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-70
  title: Service 70
  description: Component for Backstage 70
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
