---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-130
  title: Service 130
  description: Component for Backstage 130
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
