---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-81
  title: Service 81
  description: Component for Backstage 81
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
