---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-96
  title: Service 96
  description: Component for Backstage 96
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
