---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-76
  title: Service 76
  description: Component for Backstage 76
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
