---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-48
  title: Service 48
  description: Component for Backstage 48
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
