---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-115
  title: Service 115
  description: Component for Backstage 115
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
