---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-20
  title: Service 20
  description: Component for Backstage 20
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
