---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-177
  title: Service 177
  description: Component for Backstage 177
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
