---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-151
  title: Service 151
  description: Component for Backstage 151
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
