---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-54
  title: Service 54
  description: Component for Backstage 54
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
