---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-170
  title: Service 170
  description: Component for Backstage 170
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
