---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-197
  title: Service 197
  description: Component for Backstage 197
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
