---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-13
  title: Service 13
  description: Component for Backstage 13
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
