---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-78
  title: Service 78
  description: Component for Backstage 78
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
