---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-30
  title: Service 30
  description: Component for Backstage 30
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
