---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-172
  title: Service 172
  description: Component for Backstage 172
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
