---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-50
  title: Service 50
  description: Component for Backstage 50
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
