---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-118
  title: Service 118
  description: Component for Backstage 118
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
