---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-199
  title: Service 199
  description: Component for Backstage 199
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
