---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-179
  title: Service 179
  description: Component for Backstage 179
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
