---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-145
  title: Service 145
  description: Component for Backstage 145
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
