---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-60
  title: Service 60
  description: Component for Backstage 60
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
