---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-154
  title: Service 154
  description: Component for Backstage 154
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
