---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-71
  title: Service 71
  description: Component for Backstage 71
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
