---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-72
  title: Service 72
  description: Component for Backstage 72
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
