---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-49
  title: Service 49
  description: Component for Backstage 49
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
