---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-47
  title: Service 47
  description: Component for Backstage 47
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
