---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-146
  title: Service 146
  description: Component for Backstage 146
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
