---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-190
  title: Service 190
  description: Component for Backstage 190
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
