---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-107
  title: Service 107
  description: Component for Backstage 107
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
