---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-103
  title: Service 103
  description: Component for Backstage 103
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
