---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-178
  title: Service 178
  description: Component for Backstage 178
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
