---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-21
  title: Service 21
  description: Component for Backstage 21
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
