---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-182
  title: Service 182
  description: Component for Backstage 182
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
