---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-176
  title: Service 176
  description: Component for Backstage 176
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
