---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-183
  title: Service 183
  description: Component for Backstage 183
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
