---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-186
  title: Service 186
  description: Component for Backstage 186
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
