---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-32
  title: Service 32
  description: Component for Backstage 32
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
