---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-126
  title: Service 126
  description: Component for Backstage 126
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
