---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-109
  title: Service 109
  description: Component for Backstage 109
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
