---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-119
  title: Service 119
  description: Component for Backstage 119
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
