---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-189
  title: Service 189
  description: Component for Backstage 189
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
