---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-55
  title: Service 55
  description: Component for Backstage 55
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
