---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-150
  title: Service 150
  description: Component for Backstage 150
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
