---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-2
  title: Service 2
  description: Component for Backstage 2
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
