---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-88
  title: Service 88
  description: Component for Backstage 88
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
