---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-185
  title: Service 185
  description: Component for Backstage 185
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
