---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-133
  title: Service 133
  description: Component for Backstage 133
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
