---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-79
  title: Service 79
  description: Component for Backstage 79
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
