---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-93
  title: Service 93
  description: Component for Backstage 93
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
