---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-46
  title: Service 46
  description: Component for Backstage 46
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
