---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-180
  title: Service 180
  description: Component for Backstage 180
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
