---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-191
  title: Service 191
  description: Component for Backstage 191
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
