---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-63
  title: Service 63
  description: Component for Backstage 63
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
