---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-127
  title: Service 127
  description: Component for Backstage 127
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
