---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-162
  title: Service 162
  description: Component for Backstage 162
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
