---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-25
  title: Service 25
  description: Component for Backstage 25
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
