---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-171
  title: Service 171
  description: Component for Backstage 171
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
