---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-73
  title: Service 73
  description: Component for Backstage 73
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
