---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-138
  title: Service 138
  description: Component for Backstage 138
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
