---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-149
  title: Service 149
  description: Component for Backstage 149
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
