---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-134
  title: Service 134
  description: Component for Backstage 134
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
