---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-194
  title: Service 194
  description: Component for Backstage 194
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
