---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-53
  title: Service 53
  description: Component for Backstage 53
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
