---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-113
  title: Service 113
  description: Component for Backstage 113
  annotations:
    github.com/project-slug: RoadieHQ/monorepo-sample-service
spec:
  type: service
  owner: engineering
  lifecycle: experimental
